name: Secure Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-security-scan:
    name: Terraform Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: aws

      - name: Terraform Validate
        run: terraform validate
        working-directory: aws

      - name: Terraform Plan
        run: terraform plan
        working-directory: aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: aws
